config/routes.rb
Rails.application.routes.draw do


  get 'legals/new'
  get 'legals/create'
  get 'legals/index'
  get 'contact/index'
  get 'contact/create'
  get 'home/index'
  ActiveAdmin.routes(self)
  resources :line_items
  resources :carts
  devise_for :users
  # le code ci-dessous n'est pas necessaire, je le garde au cas ou ca rebug, mais il est destiné a etre supprimé
  # devise_scope :users do
  #   get '/users/sign_out' => 'devise/sessions#delete'
  # end

  root to: 'products#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    resources :bookings, only: [ :new, :create ]
  end
  resources :bookings, only: [:destroy, :index, :booking_by_user, :update]

get 'pages/cgu'
get 'pages/user'
get 'pages/zoneadmin'
get 'pages/contact'
get 'pages/equipe'
get 'pages/faq'
get 'pages/projet'
get 'pages/prix'

  get 'contacts' => 'contacts#index'
  get 'contacts/new'
  post 'contacts' => 'contacts#create'
  delete 'contacts/:id' => 'contacts#destroy'

  get 'legals' => 'legals#index'
  get 'legals/new'
  post 'legals' => 'legals#create'
  delete 'legals/:id' => 'legals#destroy'
  get 'legals/:id' => 'legals#show_admin'
  patch 'legals/:id' => 'legals#update'

  get 'faqs' => 'faqs#index'
  get 'faqs/new'
  post 'faqs' => 'faqs#create'
  get 'faqs/index_admin' => 'faqs#index_admin'
  get 'faqs/index_admin/:id' => 'faqs#show_admin'
  patch 'faqs/:id' => 'faqs#update'
  delete 'faqs/:id' => 'faqs#destroy'

#le nesting ci dessous est un essaie, si ca ne fonctionnepas, on l'enlevera

  #get 'products/new' => 'products#new'
  #post 'products/new' => 'products#create'

  #get 'products' => 'products#index'
  #post 'products' => 'products#create'

  #get 'products/:id' => 'products#show'
  patch 'products/:id' => 'products#update'

  #delete 'products/:id' => 'products#destroy'
  get 'productsby/:id' => 'products#index_by_categorie'
  get 'index_admin' => 'products#index_admin'
  get 'index_admin/:id' => 'products#show_admin'

  get 'zones' => 'zones#index'
  get 'zones/new'
  post 'zones' => 'zones#create'
  get 'zones/:id' => 'zones#show'
  patch 'zones/:id' => 'zones#update'
  delete 'zones/:id' => 'zones#destroy'

  #get 'categories' => 'categories#index'
  #get 'categories/new'
  #post 'categories/new' => 'categories#create'
  #post 'categories' => 'categories#create'
  #get 'categories/:id' => 'categories#show'
  #patch 'categories/:id' => 'categories#update'
  #delete 'categories/:id' => 'categories#destroy'

  resources :categories


  #resources :bookings


  get 'booking_by_user' => 'bookings#booking_by_users'

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

mount StripeEvent::Engine, at: '/stripe-webhooks'


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

    <ul class="footer-links-list">
        <!-- CGU -->
        <li>
          <%= link_to "AGB/Datenschutz", "/pages/cgu " %>
        </li>
        <!-- L'equipe -->
        <li>
          <%= link_to "Über uns", "/pages/equipe" %>
        </li>
        <!-- Le projet -->
        <li>
          <%= link_to "Das Projekt", "/pages/projet" %>
        </li>
    </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <div class="col-2 ">
  <%= link_to "/products", class: "navbar-brand" do %>
    <%= image_tag "logoMeinMarseille.png"%>
    <% end %>
  </div>



  <div class="navbar-categories col-lg-8 ">
    <ul class="navbar-categories-list navbar-nav mr-auto" >

      <li classe="categories">
        <div class="dropdown">
<!-- qui sommes nous ? -->
            <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" >
             Über uns?
            </div>
<!-- le projet et l'equipe -->
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "Das Projekt", pages_projet_path, class: "dropdown-item" %>
              <%= link_to "Das Team", pages_equipe_path, class: "dropdown-item" %>
            </div>

        </div>
      </li>

      <li classe="categories">
        <div class="dropdown">
<!-- visittes -->
            <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" >
             Führungen
            </div>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <% @visites10.each do |visite| %>
              <a class="dropdown-item" href="/products/<%= visite.id %>"><%= visite.title %></a>
              <% end %>
            </div>

        </div>
      </li>
<!-- prix -->
      <li classe="catego ">
          <%= link_to "Preise", pages_prix_path, class: "dropdown-item" %>
      </li>

<!-- FAQ -->
      <li classe="catego ">
        <%= link_to "F A Q", faqs_path, class: "dropdown-item" %>
      </li>
<!-- contact -->
       <li classe="catego ">
        <%= link_to "Kontakt", pages_contact_path, class: "dropdown-item" %>
      </li>

    </ul>
  </div>




  <div class="collapse navbar-collapse col-lg-2 " id="navbarSupportedContent">
    <div class="socialnetworks col-6">
    <div class="facebook"> <a href="https://www.facebook.com/meinmarseille/" target = "_blank"> <%= image_tag "facebook.svg"%></a></div>
    <div class="insta"> <a href="https://www.instagram.com/meinmarseille/" target = "_blank"> <%= image_tag "instagram.svg"%></a></div>
  </div>
    <ul class="navbar-nav mr-auto col-6">
      <% if user_signed_in? %>

        <li class="nav-item dropdown">
          <%= image_tag "icone menu.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

            <%if current_user.admin %>
            <%= link_to "Zone Admin", pages_zoneadmin_path, class: "dropdown-item" %>

            <p> </p>
            <% else %>
            <% end %>
            <%= link_to "Meine Buchungen", booking_by_user_path, class: "dropdown-item " %>
            <%= link_to "Mein Warenkorb", "/carts/#{session[:cart_id]} ", class: "dropdown-item" %>
            <%= link_to "Meine Infos", "pages/user", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>




  <li class="nav-item dropdown mobile-nav col-3">


            <%= image_tag "icone menu.png", class: "dropdown-toggle", id: "navbarDropdown2", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>


          <div class="dropdown-menu dropdown-menu-right  " aria-labelledby="navbarDropdown2">
              <%= link_to "Preise", pages_prix_path, class: "dropdown-item " %>
              <%= link_to "F A Q", faqs_path, class: "dropdown-item" %>
              <%= link_to "Kontakt", pages_contact_path, class: "dropdown-item" %>
              <%= link_to "Das Projekt", pages_projet_path, class: "dropdown-item" %>
              <%= link_to "Das Team", pages_equipe_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
            <% if user_signed_in? %>
              <%= link_to "Meine Buchungen", booking_by_user_path, class: "dropdown-item" %>
              <%= link_to "Mein Warenkorb", "/carts/#{session[:cart_id]} ", class: "dropdown-item" %>
              <%= link_to "Meine Infos", "pages/user", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%else%>
              <%= link_to "Login", new_user_session_path, class: " dropdown-item" %>
            <% end %>
          </div>
  </li>


</div>