config/routes.rb
Rails.application.routes.draw do


  get 'legals/new'
  get 'legals/create'
  get 'legals/index'
  get 'contact/index'
  get 'contact/create'
  get 'home/index'
  ActiveAdmin.routes(self)
  resources :line_items
  resources :carts
  devise_for :users
  # le code ci-dessous n'est pas necessaire, je le garde au cas ou ca rebug, mais il est destiné a etre supprimé
  # devise_scope :users do
  #   get '/users/sign_out' => 'devise/sessions#delete'
  # end

  root to: 'products#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products do
    resources :bookings, only: [ :new, :create ]
  end
  resources :bookings, only: [:destroy, :index, :booking_by_user, :update]

get 'pages/cgu'
get 'pages/user'
get 'pages/zoneadmin'
get 'pages/contact'
get 'pages/equipe'
get 'pages/faq'
get 'pages/projet'
get 'pages/prix'

  get 'contacts' => 'contacts#index'
  get 'contacts/new'
  post 'contacts' => 'contacts#create'
  delete 'contacts/:id' => 'contacts#destroy'

  get 'legals' => 'legals#index'
  get 'legals/new'
  post 'legals' => 'legals#create'
  delete 'legals/:id' => 'legals#destroy'
  get 'legals/:id' => 'legals#show_admin'
  patch 'legals/:id' => 'legals#update'

  get 'faqs' => 'faqs#index'
  get 'faqs/new'
  post 'faqs' => 'faqs#create'
  get 'faqs/index_admin' => 'faqs#index_admin'
  get 'faqs/index_admin/:id' => 'faqs#show_admin'
  patch 'faqs/:id' => 'faqs#update'
  delete 'faqs/:id' => 'faqs#destroy'

#le nesting ci dessous est un essaie, si ca ne fonctionnepas, on l'enlevera

  #get 'products/new' => 'products#new'
  #post 'products/new' => 'products#create'

  #get 'products' => 'products#index'
  #post 'products' => 'products#create'

  #get 'products/:id' => 'products#show'
  patch 'products/:id' => 'products#update'

  #delete 'products/:id' => 'products#destroy'
  get 'productsby/:id' => 'products#index_by_categorie'
  get 'index_admin' => 'products#index_admin'
  get 'index_admin/:id' => 'products#show_admin'

  get 'zones' => 'zones#index'
  get 'zones/new'
  post 'zones' => 'zones#create'
  get 'zones/:id' => 'zones#show'
  patch 'zones/:id' => 'zones#update'
  delete 'zones/:id' => 'zones#destroy'

  #get 'categories' => 'categories#index'
  #get 'categories/new'
  #post 'categories/new' => 'categories#create'
  #post 'categories' => 'categories#create'
  #get 'categories/:id' => 'categories#show'
  #patch 'categories/:id' => 'categories#update'
  #delete 'categories/:id' => 'categories#destroy'

  resources :categories


  #resources :bookings


  get 'booking_by_user' => 'bookings#booking_by_users'

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

mount StripeEvent::Engine, at: '/stripe-webhooks'


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index


    @categories = Categorie.page(params[:page]).per(12)
  end
  #ici je charge une variable categorie avec une repartition par page, au lancement de l'index

  def new

    @categorie = Categorie.new
  end

  def create

    categorie = Categorie.create(categorie_params)
    redirect_to "/categories"
  end

  def show
    @categorie = Categorie.find(params[:id])
  end

  def update
    Categorie.find(params[:id]).update name: params[:name], description: params[:description]
    redirect_to "/categories"
  end

  def destroy
    Categorie.find(params[:id]).destroy
    redirect_to "/categories"
  end

  def categorie_params
    params.require(:categorie).permit(:name, :description)
  end

end

app/views/categories/index.html.erb
<h1>Liste des categories</h1>
<p>Find me in app/views/categories/index.html.erb</p>

<div class="cards">
    <%= paginate @categories %>
    <% @categories.each do |categorie| %>
    <div class="card" style="width: 18rem;">
      <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><a href="/categories/<%= categorie.id %>"><%= categorie.name%></a></h5>
        <p class="card-text"><%= categorie.description%></p>

        <a href="/categories/<%= categorie.id %>" class="btn btn-primary">voire</a>
      </div>
    </div>
    <% end %>
  </div>
</div>


<p> <a href= "<%= new_category_path %>" class="btn btn-primary"> Creer une nouvelle categorie</a>

app/views/categories/new.html.erb
<h1>Creer une nouvelle categorie</h1>




<%= form_for @categorie do |f| %>
<div class="form-group">

<label> Nom de la categorie </label>
<%= f.text_field :name, class: 'form-control' %>

</div>

<div class="form-group">

<label> description de la categorie </label>
<%= f.text_area :description, class: 'form-control' %>

</div>

<div class="form-group">

<button type="submit" class="btn btn-primary"> creer </button>


</div>

<% end %>

app/views/categories/show.html.erb
<h1><%=@categorie.name%></h1>
<p><%=@categorie.description%></p>


<p> Modifier ma categorie</p>

<%= form_tag "/categories/#{@categorie.id}", method: "patch" do %>
  <input type="text" name="name" value="<%= @categorie.name %>" />
  <input type="text" name="description" value="<%= @categorie.description %>" />
  <input type="submit" value="mettre a jour la categorie" />
<% end %>

<%= form_tag "/categories/#{@categorie.id}", method: "delete" do %>
  <input type="submit" value="Supprimer la categorie" />
<% end %>